### ISSUE TITLE
Agregar Gui contactos

### ISSUE THREAD

**Issue by AndresArdila544** [AndresArdila544/Organizador-POO#13]
Agregar una interfaz parecida a la de Invitados.java donde le muestre al usuario los contactos guardados y le de la opción de crear un nuevo contacto.

Se ejecuta desde:
Linea 228 : PrincipalPantalla.java

**Comment by idsolanov** [comment]
tambien voy a hacer la pantalla de editar evento, ya usted me dira desde donde la llaman ya sea desde la pantalla principal o de otro lado

**Comment by AndresArdila544** [comment]
La pantalla de editar evento se llama desde una pantalla que muestra todos los datos del evento.
En la pantalla principal el usuario selecciona los eventos que desea ver en mayor detalle. Para cada uno se abre una interfaz con el icono, descripción, invitados, fecha, etc.. De ahi se llama la pantalla de editar evento, y en esa pantalla esta la opción de eliminar evento.

**Comment by idsolanov** [comment]
esa seria como visualizar evento, hago esa tambien?

**Comment by AndresArdila544** [comment]
Si quiere, vea el codigo de la pantalla principal y parta de ahi
